import { Currency } from './../models/currency';
export const CurrencyMap: Currency[] = [
  { id: 'AED', name: 'Emirati dirham', country: 'UAE', symbol: 'د.إ' },
  { id: 'AUD', name: 'Australian dollars', country: 'Australia', symbol: '$' },
  { id: 'BDT', name: 'Bangladeshi taka', country: 'Bangladesh', symbol: '৳' },
  { id: 'BGN', name: 'Bulgarian lev', country: 'Bulgaria', symbol: 'лв' },
  { id: 'BRL', name: 'Brazilian real', country: 'Brazil', symbol: 'R$' },
  { id: 'CAD', name: 'Canadian dollars', country: 'Canada', symbol: '$' },
  { id: 'CHF', name: 'Swiss franc', country: 'Switzerland', symbol: 'CHF' },
  { id: 'CLP', name: 'Chilean peso', country: 'Chile', symbol: '$' },
  { id: 'CNY', name: 'Chinese yuan', country: 'China', symbol: '¥ /元' },
  { id: 'COP', name: 'Colombian peso', country: 'Colombia', symbol: '$' },
  { id: 'CZK', name: 'Czech koruna', country: 'Czechia', symbol: 'Kč' },
  { id: 'DKK', name: 'Danish krone', country: 'Denmark', symbol: 'kr' },
  { id: 'EUR', name: 'Euro', country: 'Euro area countries', symbol: '€' },
  {
    id: 'GBP',
    name: 'Pounds sterling',
    country: 'United Kingdom',
    symbol: '£',
  },
  { id: 'GEL', name: 'Georgian lari', country: 'Georgia', symbol: '₾' },
  {
    id: 'HKD',
    name: 'Hong Kong dollar',
    country: 'Hong Kong',
    symbol: '$ / HK$ / “元”8',
  },
  { id: 'HRK', name: 'Croatian Kuna', country: 'Croatia', symbol: 'kn' },
  { id: 'HUF', name: 'Hungarian forint', country: 'Hungary', symbol: 'ft' },
  { id: 'IDR', name: 'Indonesian rupiah', country: 'Indonesia', symbol: 'Rp' },
  { id: 'ILS', name: 'Israeli shekel', country: 'Israel', symbol: '₪' },
  { id: 'INR', name: 'Indian rupee', country: 'India', symbol: '₹' },
  { id: 'JPY', name: 'Japanese yen', country: 'Japan', symbol: '¥' },
  { id: 'KES', name: 'Kenyan shilling', country: 'Kenya', symbol: 'Ksh' },
  { id: 'KRW', name: 'South Korean won', country: 'South Korea', symbol: '₩' },
  { id: 'LKR', name: 'Sri Lankan rupee', country: 'Sri Lanka', symbol: 'Rs' },
  { id: 'MAD', name: 'Moroccan dirham', country: 'Morocco', symbol: '.د.م' },
  { id: 'MXN', name: 'Mexican peso', country: 'Mexico', symbol: '$' },
  { id: 'MYR', name: 'Malaysian ringgit', country: 'Malaysia', symbol: 'RM' },
  { id: 'NGN', name: 'Nigerian naira', country: 'Nigeria', symbol: '₦' },
  { id: 'NOK', name: 'Norwegian krone', country: 'Norway', symbol: 'kr' },
  {
    id: 'NZD',
    name: 'New Zealand dollar',
    country: 'New Zealand',
    symbol: '$',
  },
  { id: 'PEN', name: 'Peruvian sol', country: 'Peru', symbol: 'S/.' },
  { id: 'PHP', name: 'Philippine peso', country: 'Philippines', symbol: '₱' },
  { id: 'PKR', name: 'Pakistani rupee', country: 'Pakistan', symbol: 'Rs' },
  { id: 'PLN', name: 'Polish zloty', country: 'Poland', symbol: 'zł' },
  { id: 'RON', name: 'Romanian leu', country: 'Romania', symbol: 'lei' },
  { id: 'RUB', name: 'Russian ruble', country: 'Russia', symbol: '₽' },
  { id: 'SEK', name: 'Swedish krona', country: 'Sweden', symbol: 'kr' },
  { id: 'SGD', name: 'Singapore dollar', country: 'Singapore', symbol: '$' },
  { id: 'THB', name: 'Thai baht', country: 'Thailand', symbol: '฿' },
  { id: 'TRY', name: 'Turkish lira', country: 'Turkey', symbol: '₺' },
  { id: 'UAH', name: 'Ukrainian hryvna', country: 'Ukraine', symbol: '₴' },
  { id: 'USD', name: 'US dollar', country: 'USA', symbol: '$' },
  { id: 'VND', name: 'Vietnamese dong', country: 'Vietnam', symbol: '₫' },
  {
    id: 'ZAR',
    name: 'South African rand**',
    country: 'South Africa',
    symbol: 'R',
  },
];
