import { Currency } from './../models/currency';
export const CurrencyMap: Currency[] = [
  { id: 'AUD', name: 'Australian dollar', country: 'Australia', symbol: '$' },
  { id: 'BGN', name: 'Bulgarian lev', country: 'Bulgaria', symbol: 'лв' },
  { id: 'BRL', name: 'Brazilian real', country: 'Brazil', symbol: 'R$' },
  { id: 'CAD', name: 'Canadian dollar', country: 'Canada', symbol: '$' },
  { id: 'CHF', name: 'Swiss franc', country: 'Switzerland', symbol: 'CHF' },
  { id: 'CNY', name: 'Chinese yuan', country: 'China', symbol: '¥ /元' },
  { id: 'CZK', name: 'Czech koruna', country: 'Czechia', symbol: 'Kč' },
  { id: 'DKK', name: 'Danish krone', country: 'Denmark', symbol: 'kr' },
  { id: 'EUR', name: 'Euro', country: 'Euro area countries', symbol: '€' },
  {
    id: 'GBP',
    name: 'Pounds sterling',
    country: 'United Kingdom',
    symbol: '£',
  },
  {
    id: 'HKD',
    name: 'Hong Kong dollar',
    country: 'Hong Kong',
    symbol: '$ / HK$ / “元”8',
  },
  { id: 'HRK', name: 'Croatian Kuna', country: 'Croatia', symbol: 'kn' },
  { id: 'HUF', name: 'Hungarian forint', country: 'Hungary', symbol: 'ft' },
  { id: 'IDR', name: 'Indonesian rupiah', country: 'Indonesia', symbol: 'Rp' },
  { id: 'ILS', name: 'Israeli shekel', country: 'Israel', symbol: '₪' },
  { id: 'INR', name: 'Indian rupee', country: 'India', symbol: '₹' },
  { id: 'ISK', name: 'Icelandic Krona', country: 'Iceland', symbol: 'kr' },
  { id: 'JPY', name: 'Japanese yen', country: 'Japan', symbol: '¥' },
  { id: 'KRW', name: 'South Korean won', country: 'South Korea', symbol: '₩' },
  { id: 'MXN', name: 'Mexican peso', country: 'Mexico', symbol: '$' },
  { id: 'MYR', name: 'Malaysian ringgit', country: 'Malaysia', symbol: 'RM' },
  { id: 'NOK', name: 'Norwegian krone', country: 'Norway', symbol: 'kr' },
  {
    id: 'NZD',
    name: 'New Zealand dollar',
    country: 'New Zealand',
    symbol: '$',
  },
  { id: 'PHP', name: 'Philippine peso', country: 'Philippines', symbol: '₱' },
  { id: 'PLN', name: 'Polish zloty', country: 'Poland', symbol: 'zł' },
  { id: 'RON', name: 'Romanian leu', country: 'Romania', symbol: 'lei' },
  { id: 'RUB', name: 'Russian ruble', country: 'Russia', symbol: '₽' },
  { id: 'SEK', name: 'Swedish krona', country: 'Sweden', symbol: 'kr' },
  { id: 'SGD', name: 'Singapore dollar', country: 'Singapore', symbol: '$' },
  { id: 'THB', name: 'Thai baht', country: 'Thailand', symbol: '฿' },
  { id: 'TRY', name: 'Turkish lira', country: 'Turkey', symbol: '₺' },
  { id: 'USD', name: 'US dollar', country: 'USA', symbol: '$' },
  {
    id: 'ZAR',
    name: 'South African rand**',
    country: 'South Africa',
    symbol: 'R',
  },
];
